import Footer from '@/components/Footer';
import Header from '@/components/Navbar';
import { cn } from '@/libs/utils';
import '@/styles/globals.css';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: './icon.png',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          'dark:bg-black text-primary dark:text-primary-dark w-screen h-screen overflow-y-auto overflow-x-hidden ',
          inter.className,
        )}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
